version: '3.8'

networks:
  default:
    name: tidio_payroll

services:
  nginx:
    container_name: tidio_payroll_nginx
    depends_on:
      - php
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: nginx:stable-alpine
    ports:
      - "8888:80"
    volumes:
      - ../:/var/www/payroll:ro,cached
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro

  php:
    build:
      context: ./php
    command: php-fpm
    container_name: tidio_payroll_php
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - COMPOSER_HOME=/tmp/composer
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/payroll/bin
    image: payroll-php:8-fpm-alpine
    user: "${PUID}:${PGID}"
    volumes:
      - ../:/var/www/payroll
      - ./php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    working_dir: /var/www/payroll
